site_name: BlindSpot - Text Classifier Auditing Framework
site_description: A Behavioral and Explainable-AI Framework for Auditing Text Classifiers
site_author: Ziya Fathima M P

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Failure Taxonomy: taxonomy.md
  - Usage Guide: usage.md
  - API Reference: api.md
